# Generated by Django 2.2.6 on 2019-10-03 09:34

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191002_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.URLField(default=datetime.datetime(2019, 10, 3, 9, 34, 19, 548762, tzinfo=utc), verbose_name='Image Url Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='Video Url Linl'),
            preserve_default=False,
        ),
    ]
